### ISSUE TITLE
Clearfix in `AnimatedContainer` can cause alignment issue with flexbox

### ISSUE THREAD

**Issue by emattias** [ember-animation/ember-animated#219]
https://github.com/ember-animation/ember-animated/blob/e15f1d5432cbb3fdf3209a109d4f1a638a0d9df5/vendor/ember-animated.css#L17-L20

The above css causes [this alignment issue](https://stackoverflow.com/questions/38872653/why-inline-flex-element-with-clearfix-has-a-weird-white-space) for me. So I have done this:

```css
  .animated-container::before, .animated-container::after {
    display: none !important;
    content: "" !important;
  }
```

and the animations still work. Is this clearfix still relevant when not using floats?

Maybe have it be an opt in with some `@clearfix={{true}}` argument? Or maybe just remove it? :)
